application: govlab-intranet
version: 1
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: on

skip_files:
- ^(.*/)?\.scss$
- ^(.*/)?\.scssc$

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

# static_dir does not accept regex grouping.
- url: /css
  static_dir: css

- url: /includes
  static_dir: includes

- url: /assets
  static_dir: assets

- url: /scss
  static_dir: scss

- url: /((index|faq|library|gallery|courses)\.html)
  static_files: static_site/\1
  upload: static_site/.*

- url: /library.json
  static_files: library.json
  upload: library.json

- url: /test_group.html
  static_files: test_group.html
  upload: test_group.html

- url: /fall-2014-class
  script: main.app
  login: required

- url: /snippet/.*
  script: snippet.app
  login: required

- url: /feedback
  script: feedback.app

- url: /viewFeedback
  script: feedback.app

- url: /profile
  script: main.app
  login: required

- url: /canvas
  script: main.app
  login: required

- url: /googleplus
  script: googleplus.app
  login: required

- url: /oauth2callback
  script: googleplus.app
  login: required

- url: /dashboard
  script: main.app
  login: required

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
- name: pycrypto
  version: latest